---
- set_fact:
    the_groovy_script: "artifactory-global-configuration.groovy"

- name: "Generate groovy script for Artifactory global configuration"
  template:
    src: "{{ the_groovy_script }}.j2"
    dest: "/tmp/{{ the_groovy_script }}"
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"
    #mode: 0755

- name: "Execute the script: /tmp/{{ the_groovy_script }}"
  shell: >
    java -jar {{ cj_cli_jar_location }} \
    -s http://{{ cj_cli_hostname }}:{{ cj_http_port }}{{ cj_application_context | default('') }}/ \
    groovy /tmp/{{ the_groovy_script }}
  register: result
  become: true
  become_user: "{{ cj_runas_user }}"

- debug: var=result