---
- name: "Create credential..."
  debug: var=credential

- set_fact:
    the_groovy_script: "add-credential.groovy"

- name: "Generate groovy script to add a credential"
  template:
    src: "{{ the_groovy_script }}.j2"
    dest: "/tmp/{{ the_groovy_script }}"
    owner:  "{{ jenkins_runas_user | d('jenkins')}}"
    group:  "{{ jenkins_runas_group | d('jenkins')}}"

- name: "Execute the script: /tmp/{{ the_groovy_script }}"
  shell: >
    java -jar {{ jenkins_cli_jar_location }} -s http://{{ jenkins_cli_hostname }}:{{ jenkins_http_port }}{{ jenkins_application_context | default('') }}/ groovy /tmp/{{ the_groovy_script }}
  #ignore_errors: true
  register: result

- name: "Print result"
  debug: var=result.stdout_lines

