---
- service:
    name: jenkins
    state: restarted
  notify: "service jenkins restart"
- meta: flush_handlers

- include: "cj-add-credential.yml"
  with_items:
    - "{{ cj_nodes_credentials }}"
  loop_control:
    loop_var: credential