---
- name: "Cleanup"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ cj_home }}"
  - "{{ cj_log_dir }}"
  - "{{ cj_cache_dir }}"
  - /tmp/default.json
  tags:
  - cleanup
  notify: "stop jenkins"
- meta: flush_handlers

- name: "remove jenkins package"
  package:
    name: jenkins
    state: absent
  tags:
  - cleanup
