---
- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 86400
  retries: 10
  delay: 3

- name: "install deps"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-httplib2
    - python-pip
    - acl
    - vim
    - curl
    - unzip

- name: "Add Jenkins apt Key"
  apt_key:
    url: "{{ cj_repo_key_url }}"
    state: present
  become: true

- name: "Add Jenkins apt repo"
  apt_repository:
    repo: "{{ cj_repo_url }}"
    state: present
    update_cache: yes
  become: true

- name: "Jenkins Install"
  apt:
    name: jenkins
    state: latest


