---

# we are going to re-configure jenkins on every initialization !
# See: https://wiki.jenkins-ci.org/display/JENKINS/Post-initialization+script

- name: "Create Jenkins init script dir"
  file:
    path: "{{ cj_init_dir }}"
    state: directory
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"
    mode: 0755

- name: "Generate groovy script for Jenkins own use database authorization"
  template:
    src: "{{ item }}.j2"
    dest: "{{ cj_init_dir }}/{{ item }}"
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"
  with_items:
    - 00-basic-security.groovy
  when: (cj_basic_auth is defined) and (cj_basic_auth | bool)

- name: "Generate groovy script for Active Directory authorization"
  template:
    src: "{{ item }}.j2"
    dest: "{{ cj_init_dir }}/{{ item }}"
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"
  with_items:
    - 00-AD-security.groovy
  when: (cj_AD_auth is defined) and (cj_AD_auth | bool)
