---

# we are going to re-configure jenkins on every initialization !
# See: https://wiki.jenkins-ci.org/display/JENKINS/Post-initialization+script

- name: "Create Jenkins init script dir"
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner:  "{{ jenkins_runas_user | d('jenkins')}}"
    group:  "{{ jenkins_runas_group | d('jenkins')}}"
    mode: 0755

- name: "Generate groovy script for jenkins bootstrap execution"
  template:
    src: "{{ item }}.j2"
    dest: "{{ jenkins_init_dir }}/{{ item }}"
    owner:  "{{ jenkins_runas_user | d('jenkins')}}"
    group:  "{{ jenkins_runas_group | d('jenkins')}}"
  notify: "service jenkins restart"
  with_items:
    - basic-security.groovy

- service:
    name: jenkins
    state: restarted
  notify: "service jenkins restart"
- meta: flush_handlers


#- name: "Login from CLI"
#  include: "cj-cli-login.yml"