---
- name: "Create Jenkins updates folder + plugins temporary download folder"
  file:
    path: "{{ item }}"
    owner: "{{ jenkins_runas_user  | d('jenkins')}}"
    group: "{{ jenkins_runas_group | d('jenkins')}}"
    state: directory
    mode: 0755
  with_items:
    - "{{ jenkins_home }}/updates"
    - "{{ jenkins_plugins_tmp_folder }}"

- name: "Update Jenkins plugin update-center json"
  get_url:
    url: "{{ jenkins_update_center_url | d('https://updates.jenkins-ci.org') }}/update-center.json"
    dest: "/tmp/default.json"
    owner: "{{ jenkins_runas_user  | d('jenkins')}}"
    group: "{{ jenkins_runas_group | d('jenkins')}}"
    mode: 0755
    validate_certs: false
  register: update_site

- name: "remove blank lines in default.json"
  lineinfile:
    dest: "/tmp/default.json"
    regexp: '^(?:[\t ]*(?:\r?\n|\r))+'
    state: absent
    owner: "{{ jenkins_runas_user  | d('jenkins')}}"
    group: "{{ jenkins_runas_group | d('jenkins')}}"
    mode: 0755
  when: update_site.changed

- include: "cj-auth_check.yml"

- name: "POST the default.json to Jenkins update url"
  shell: >
    cat /tmp/default.json | curl -X POST -H 'Accept: application/json' -d @- http://{{ jenkins_cli_hostname }}:{{ jenkins_http_port }}{{ jenkins_application_context | default('') }}/updateCenter/byId/default/postBack --verbose

#  uri:
#    url: "http://{{ jenkins_cli_hostname }}:{{ jenkins_http_port }}{{ jenkins_application_context | default('') }}/updateCenter/byId/default/postBack"
#    HEADER_Content-Type: "Accept: application/json"
#    method: POST
#    body: "{{ lookup('file','/tmp/default.json') }}"
#    status_code: 201
#    body_format: json
