---

- include: "cj-update_site.yml"
- include: "cj-plugin_sets.yml"

- name: "get installed plugin list"
  shell: >
    java -jar {{ cj_cli_jar_location }} \
    -s http://{{ cj_cli_hostname }}:{{ cj_http_port }}{{ cj_application_context | default('') }}/ \
    list-plugins | awk '{print $1}'
  register: plugins_installed
  changed_when: false

- name: "Install Jenkins plugins | method implemented for online installations"
  command: >
    java -jar {{ cj_cli_jar_location }} \
    -s http://{{ cj_cli_hostname }}:{{ cj_http_port }}{{ cj_application_context | default('') }}/ \
    install-plugin {{ cj_plugins | map(attribute='name') | join(' ') }}
  register: ips
  until: ips.rc == 0
  retries: 3
  delay: 3
