# depnding on run as user key paths differ ...
- set_fact:
    ssh_key_dir: "/home/{{ jenkins_runas_user }}/.ssh"
    priv_key_path: "/home/{{ jenkins_runas_user }}/.ssh/id_rsa"
    pub_key_path: "/home/{{ jenkins_runas_user }}/.ssh/id_rsa.pub"
  when: (jenkins_custom_user is defined) and (jenkins_runas | bool)

- set_fact:
    ssh_key_dir: "{{ jenkins_home }}/.ssh"
    priv_key_path: "{{ jenkins_home }}/.ssh/id_rsa"
    pub_key_path: "{{ jenkins_home }}/.ssh/id_rsa.pub"
  when: not jenkins_runas

# check the ~/.ssh dir

- name: "Check if {{ ssh_key_dir }} exists"
  stat:
    path: "{{ ssh_key_dir }}"
  register: ssh_key_dir_st

- name: "Check if {{ ssh_key_dir }} has right perms, if dosen't exist create it !"
  file:
    path: "{{ ssh_key_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ jenkins_runas_user | d('jenkins')}}"
    group: "{{ jenkins_runas_group | d('jenkins')}}"
  when: ssh_key_dir_st.stat.exists == false or ssh_key_dir_st.stat.mode != '0755'

# check the ~/.ssh/id_rsa file

- name: "Check if {{ priv_key_path }} exists"
  stat:
    path: "{{ priv_key_path }}"
  register: ssh_privkey_st

- name: "Check if {{ priv_key_path }} exists"
  file:
    path: "{{ priv_key_path }}"
    state: file
    mode: "0600"
    owner: "{{ jenkins_runas_user | d('jenkins')}}"
    group: "{{ jenkins_runas_group | d('jenkins')}}"
  when: ssh_privkey_st.stat.exists == true and ssh_privkey_st.stat.mode != '0600'

- name: "Create {{ priv_key_path }} if it doesn't exists"
  shell: "ssh-keygen -b 2048 -t rsa -f {{ priv_key_path }} -q -N \"\""
  become: true
  become_user: "{{ jenkins_runas_user | d('jenkins')}}"
  when: ssh_privkey_st.stat.exists == false

# check the ~/.ssh/id_rsa.pub file

- name: "Check if {{ pub_key_path }} exists"
  stat:
    path: "{{ pub_key_path }}"
  register: ssh_pubkey_st

- name: "Check if {{ pub_key_path }} exists"
  file:
    path: "{{ pub_key_path }}"
    state: file
    mode: "0644"
    owner: "{{ jenkins_runas_user | d('jenkins')}}"
    group: "{{ jenkins_runas_group | d('jenkins')}}"
  when: ssh_pubkey_st.stat.exists == true and ssh_pubkey_st.stat.mode != '0644'

- name: "Create {{ pub_key_path }} if it doesn't exists from existing {{ priv_key_path }}"
  shell: "ssh-keygen -y -f {{ priv_key_path }} > {{ pub_key_path }}"
  become: true
  become_user: "{{ jenkins_runas_user | d('jenkins') }}"
  when: ssh_pubkey_st.stat.exists == false and ssh_privkey_st.stat.exists == true

