---
- set_fact:
    cj_update_center_url: "{{ cj_nexus_url }}/{{ cj_nexus_updates }}"
  when: cj_nexus and not cj_juseppe

- set_fact:
    cj_update_center_url: "{{ cj_juseppe_url }}"
  when: cj_nexus and cj_juseppe

- name: "Create Jenkins updates folder + plugins temporary download folder"
  file:
    path: "{{ item }}"
    owner: "{{ cj_runas_user }}"
    group: "{{ cj_runas_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ cj_home }}/updates"
    - "{{ cj_plugins_tmp_folder }}"

- name: "Update Jenkins plugin update-center json"
  get_url:
    url: "{{ cj_update_center_url | d('https://updates.jenkins-ci.org') }}/update-center.json"
    dest: "{{ cj_uc_json }}"
    owner: "{{ cj_runas_user }}"
    group: "{{ cj_runas_group }}"
    mode: 0755
    validate_certs: false
    url_username: "admin"
    url_password: "changeme"
  register: update_site

- name: "remove 'postback' unnecessary string"
  shell: sed -i 's/{{ item }}//g' {{ cj_uc_json }}
  with_items:
  - 'updateCenter.post('
  - ');'
  when: cj_nexus

- name: "remove blank lines in default.json"
  lineinfile:
    dest: "{{ cj_uc_json }}"
    regexp: '^(?:[\t ]*(?:\r?\n|\r))+'
    state: absent
    owner: "{{ cj_runas_user }}"
    group: "{{ cj_runas_group }}"
    mode: 0755
  when: update_site.changed

- block:
    - name: "Replace plugin provider url with nexus"
      replace:
        dest: "{{ cj_uc_json }}"
        regexp: 'http://updates.jenkins-ci.org/'
        replace: '{{ cj_nexus_url }}/{{ cj_nexus_updates }}/'

    - name: "Inject update-center.json"
      copy:
        src: '{{ cj_uc_json }}'
        dest: "{{ item }}"
      with_items:
      - "{{ cj_home }}/updates/{{ cj_uc_json.split('/')[2] }}"
      - "{{ cj_usercont_dir }}/update-center.json"

    - name: "deploy update site url"
      template:
        src: "{{ item }}.j2"
        dest: "{{ cj_home }}/{{ item }}"
      with_items:
      - 'hudson.model.UpdateCenter.xml'
  when: cj_nexus

- name: "POST the default.json to Jenkins update url"
  shell: >
    "cat {{ cj_uc_json }} | curl -X POST -H 'Accept: application/json' -d @- http://{{ cj_cli_hostname }}:{{ cj_http_port }}{{ cj_application_context | default('') }}/updateCenter/byId/default/postBack --verbose"
  when: not cj_nexus

- include: "cj-restart-jenkins.yml"