---
- include: "cj-auth_check.yml"

- block:
  - name: "Configure Jenkins via {{ jenkins_conf_file }}"
    template:
      src: "credentials.j2"
      dest: "{{ jenkins_plugins_tmp_folder }}/credentials.xml"
      mode: 0755
      owner: root
      group: root
    register: config_changed
    with_items:
      - "{{ jenkins_localdb_users }}"


#  - name: "Invoke cli to setup credentils ..."
#    command: >
#    java -jar {{ jenkins_cli_jar_location }} -s http://{{ jenkins_cli_hostname }}:{{ jenkins_http_port }}{{ jenkins_application_context | default('') }}/
#
#    creates="{{ jenkins_home }}/credentials.xml
##  with_items:
##    - "{{ jenkins_plugins }}"
##  when: plugins_installed and plugins_installed.stdout.find('{{ item.name }}') == -1
##  notify: "restart jenkins"
#
#  when: (jenkins_auth_enabled is not defined) and (jenkins_auth_enabled | bool)